config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#index"
  resources :recipes do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :users do
    member do
      get :likes
    end
  end
  resources :rakutens, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :likes

  validates :title, presence: true
  validates :ingredient, presence: { message: "can't be blank" }, if: ->(recipe) { recipe.instruction.present? }
  validates :instruction, presence: { message: "can't be blank" }, if: ->(recipe) { recipe.ingredient.present? }
  validates :ingredient, :instruction, :reference_url, presence: { message: "can't be blank" },
                                                       if: lambda { |recipe|
                                                             recipe.ingredient.blank? && recipe.instruction.blank? && recipe.reference_url.blank?
                                                           }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ''
      Recipe.where('title LIKE(?)', "%#{search}%")
    else
      Recipe.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :password, format: { with: /\A[a-zA-Z0-9]{6,}\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']  # 環境変数を読み込む記述に変更
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @recipe = Recipe.find(params[:recipe_id])
    return unless @comment.save

    CommentChannel.broadcast_to @recipe, { comment: @comment, user: @comment.user }
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, recipe_id: params[:recipe_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_recipe
  before_action :authenticate_user!, only: [:create]

  def create
    like = current_user.likes.build(recipe_id: params[:recipe_id])
    like.save
    redirect_to recipe_path(:recipe_id)
  end

  def destroy
    like = Like.find_by(recipe_id: params[:recipe_id], user_id: current_user.id)
    like.destroy
    redirect_to recipe_path(:recipe_id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/rakutens_controller.rb
class RakutensController < ApplicationController
  def index
    client = HTTPClient.new
    # 楽天レシピカテゴリー一覧API
    res = client.get("https://app.rakuten.co.jp/services/api/Recipe/CategoryList/20170426?format=json&applicationId=#{ENV['RAKUTEN_APPLICATION_ID']}")
    categories = JSON.parse(res.body)['result']['small']
    @hit = true
    if params[:search].present?
      # categoryNameの中で検索したワードが入っているカテゴリーを配列として取得する
      categories_list = categories.select { |x| x['categoryName'].include?(params[:search]) }
      if categories_list.empty?
        @hit = false
      else
        # 取得した配列の中からランダムで1つを抽出し、そのカテゴリーIDを取得している
        categorie_id = categories_list.sample['categoryUrl'].split('/').last
        # 取得したカテゴリーIDからそのカテゴリーの中の人気料理を取得している（楽天レシピカテゴリー別ランキングAPI）
        categories_ranktop = client.get("https://app.rakuten.co.jp/services/api/Recipe/CategoryRanking/20170426?applicationId=#{ENV['RAKUTEN_APPLICATION_ID']}&categoryId=#{categorie_id}")
        # 取得した料理を8種の形にする
        @foods = JSON.parse(categories_ranktop.body)['result']
      end
    else
      # 何も検索欄に書かれていない時、人気料理を表示する
      pop = client.get("https://app.rakuten.co.jp/services/api/Recipe/CategoryRanking/20170426?applicationId=#{ENV['RAKUTEN_APPLICATION_ID']}")
      @foods = JSON.parse(pop.body)['result']
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_item, only: [:edit, :show, :update, :destroy]

  def index
    @recipes = Recipe.all.order('created_at DESC')
    client = HTTPClient.new
    pop = client.get("https://app.rakuten.co.jp/services/api/Recipe/CategoryRanking/20170426?applicationId=#{ENV['RAKUTEN_APPLICATION_ID']}")
    @foods = JSON.parse(pop.body)['result']
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comments = @recipe.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @recipe.user_id
      @recipe.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    @recipes = Recipe.search(params[:keyword])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :ingredient, :instruction, :reference_url, :memo,
                                   :image).merge(user_id: current_user.id)
  end

  def set_item
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @recipes = @user.recipes.order('created_at DESC')
    @like_recipes = @user.likes.map { |like| like.recipe }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rakutens_helper.rb
module RakutensHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/ destroy.js.erb
document.getElementById("like-btn<%= @recipe.id %>").innerHTML = "<%= j(render partial: 'likes/like', recipe: @recipe) %>"

app/views/likes/_like.html.erb
<% if user_signed_in? && @recipe.liked_by?(current_user)%>
  <%=link_to "いいねを解除★", recipe_likes_path(@recipe.id), data: { turbo_method: :delete }, class: "recipe_likes" , remote: true %>
<% else %>
  <%=link_to "いいねをする☆", recipe_likes_path(@recipe.id), data: { turbo_method: :post }, class: "recipe_likes", remote: true %>
<% end %>

app/views/likes/create.js.erb
document.getElementById("like-btn<%= @recipe.id %>").innerHTML = "<%= j(render partial: 'likes/like', recipe: @recipe) %>"

app/views/rakutens/index.html.erb
<%= render "shared/header" %>

<div class="search-main">
  <div class="search-rakuten">
    <h2>人気のレシピを検索 💡</h2>

    <%= form_tag({controller:"rakutens",action:"index"}, method: :get) do %>
      <%= text_field_tag :search, nil, placeholder: "食材を入力してください" %> 
      <%= submit_tag '検索' %>
    <% end %>
    <div class="search-explain">食材の人気レシピTOP４が表示されます</div><br>

    <div class="recipe-search-rank">
      <% if @hit %>
        <% @foods.each do |f| %>
        <div class="search-recipes">
          🌟 第<%= f["rank"] %>位 🌟
          <div class="recipeTitle"><%= f["recipeTitle"] %> </div><br>
          <%# 写真をクリックするとレシピの詳細が見れる %>
          <%= link_to f["recipeUrl"] do %>
            <%= image_tag f["foodImageUrl"], class:"recipe-search-img" %> <br>
          <% end %>
        </div>
        <% end %>
      <% else %>
        <h3>該当するレシピがありません</h3>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/recipes/edit.html.erb
<%= render "shared/header" %>
<div class="recipes-post-contents">

  <div class="recipes-post-main">
    <h2 class="recipes-post-title">レシピを入力しよう</h2>
    <div class="hr-line"></div>


    <%= form_with model: @recipe, local: true do |form| %>

    <%= render 'shared/error_messages', model: form.object %>

    <%# レシピ名 %>
    <div class="new-recipes">
      <div class="weight-bold-text">
        レシピ名
        <span class="indispensable">必須</span>
      </div>
      <%= form.text_field :title, class:"recipes-text", placeholder: "例)白だしで作るだし巻き卵" %>
    </div>
    <%# /レシピ名 %>

    <%# 料理写真 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        料理画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= form.file_field :image, id:"recipe-image" %>
      </div>
    </div>
    <%# /料理写真 %>

    <div class="weight-bold-text">
      ※材料と作り方 or URL は必ず記入してください
      <span class="indispensable">必須</span>
    </div>

    <%# 材料と作り方 %>
    <div class="new-recipes">
      <div class="weight-bold-text">
        材料
      </div>
      <%= form.text_area :ingredient, class:"recipes-text", placeholder: "例)卵３個　白だし大さじ１　サラダ油適量", rows: "10" %>
      <div class="recipes-explain">
        <div class="weight-bold-text">
        作り方
        </div>
        <%= form.text_area :instruction, class:"recipes-text", placeholder: "例)1. ボウルに材料を混ぜる　2. 卵焼き器に油を入れ、強火　3. 3分の１ずつ入れ、手前に巻く", rows: "10" %>
      </div>
    </div>
    <%# /材料と作り方 %>

    <%# URLとメモ %>
    <div class="new-recipes">
        <div class="weight-bold-text">
          作ったレシピのURL
        </div>
        <%= form.text_field :reference_url,class:"recipes-text",  placeholder: "https:// 〜〜" %>
    </div>
    <div class="new-recipes">
          <div class="weight-bold-text">
          メモ
          </div>
          <%= form.text_area :memo, class:"recipes-text", placeholder: "ひとことメモなど記入ができます　例)〇〇を入れると美味しかった、レシピ通りだと水っぽくなってしまったので分量を少なくする　など", rows: "5" %>
    </div>
    <%# /URLとメモ %>

    <%# 下部ボタン %>
    <div class="recipe-btn-contents">
      <%= form.submit "変更する" ,class:"recipe-btn" %>
      <%=link_to 'もどる', recipe_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/recipes/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「今日の献立」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      今日の献立、何にする？
    </h2>
    <p class='service-explain'>
      迷っているあなたをお助けします
    </p>
  </div>
  <%# /画面上部の「今日の献立」帯部分 %>

  <%# レシピランキング %>
  <div class="main-recipes">
    <div class="recipe-rank">
      <h3 class="ranking-title">⭐️人気ランキング⭐️</h3>
      <% @foods.each do |f| %>
        <div class="ranking">
          <div class="ranking-rank">👑 第<%= f["rank"] %>位 👑<br></div>
          <%= f["recipeTitle"] %> <br>
          <%# 写真をクリックするとレシピの詳細が見れる %>
          <%= link_to f["recipeUrl"] do %>
            <%= image_tag f["foodImageUrl"], class:"ranking-img" %> <br>
          <% end %>
        </div>
      <% end %>
      <div class="annotation">※楽天レシピより  </div>
    </div>
    <%# /レシピランキング %>


    <%# レシピ検索機能 %>
    <div class="main-recipes-right">
      <div class="main-recipe-search">
        <h3 class="search-title">レシピを検索する 🔍</h3>
        <div class="search-contents">
          <div>
          <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "投稿されたレシピを検索", class: "search-input" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>
          </div>
          <div class="rakuten-search-contents">
            <%=link_to '食材からレシピを検索する', rakutens_path, class:"" %>
          </div>
        </div>
      </div>
      <%# /レシピ検索機能 %>

      <%# レシピ一覧 %>
      <div class="recipe-contents">
        <h2 class='title'>新着レシピ 🆕</h2>
          <ul class='recipe-lists'>
          <% @recipes.first(9).each do |recipe| %>
          <li class='list'>
            <%= link_to recipe_path(recipe.id) do %> 
            <div class='recipe-img-content'>
              <% if recipe.image.attached? %>
                <%= image_tag recipe.image, class: "recipe-img" %> 
              <% else %>
                <%= image_tag "no-image.png", class: "recipe-img" , style: 'border: 1px solid gray;' %>
              <% end %>
            </div>
            <div class='recipe-info'>
              <h4 class='recipe-title'>
                <%= recipe.title %>
              </h4>
            </div>
            <% end %>
          </li>
          <% end %>
          </ul>
      </div>
    </div>
  </div>
  <%# /レシピ一覧 %>

</div>
<%= render "shared/footer" %>

app/views/recipes/new.html.erb
<%= render "shared/header" %>
<div class="recipes-post-contents">

  <div class="recipes-post-main">
    <h2 class="recipes-post-title">レシピを入力しよう</h2>
    <div class="hr-line"></div>


    <%= form_with model: @recipe, local: true do |form| %>

    <%= render 'shared/error_messages', model: form.object %>

    <%# レシピ名 %>
    <div class="new-recipes">
      <div class="weight-bold-text">
        レシピ名
        <span class="indispensable">必須</span>
      </div>
      <%= form.text_field :title, class:"recipes-text", placeholder: "例)白だしで作るだし巻き卵" %>
    </div>
    <%# /レシピ名 %>

    <%# 料理写真 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        料理画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= form.file_field :image, id:"recipe-image" %>
      </div>
    </div>
    <%# /料理写真 %>

    <div class="weight-bold-text">
      ※材料と作り方 or URL は必ず記入してください
      <span class="indispensable">必須</span>
    </div>

    <%# 材料と作り方 %>
    <div class="new-recipes">
      <div class="weight-bold-text">
        材料
      </div>
      <%= form.text_area :ingredient, class:"recipes-text", placeholder: "例)卵３個　白だし大さじ１　サラダ油適量", rows: "10" %>
      <div class="recipes-explain">
        <div class="weight-bold-text">
        作り方
        </div>
        <%= form.text_area :instruction, class:"recipes-text", placeholder: "例)1. ボウルに材料を混ぜる　2. 卵焼き器に油を入れ、強火　3. 3分の１ずつ入れ、手前に巻く", rows: "10" %>
      </div>
    </div>
    <%# /材料と作り方 %>

    <%# URLとメモ %>
    <div class="new-recipes">
        <div class="weight-bold-text">
          作ったレシピのURL
        </div>
        <%= form.text_field :reference_url,class:"recipes-text",  placeholder: "https:// 〜〜" %>
    </div>
    <div class="new-recipes">
          <div class="weight-bold-text">
          メモ
          </div>
          <%= form.text_area :memo, class:"recipes-text", placeholder: "ひとことメモなど記入ができます　例)〇〇を入れると美味しかった、レシピ通りだと水っぽくなってしまったので分量を少なくする　など", rows: "5" %>
    </div>
    <%# /URLとメモ %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= form.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/recipes/search.html.erb
<%= render "shared/header" %>
<div class='main-recipes2'>

  <div class="search-result-recipe">
    <div class="search-recipe-form">
    <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    </div>
    <div class="search-post-recipe">
      <ul class='recipe-lists'>
      <% @recipes.each do |recipe| %>
        <li class='list'>
          <%= link_to recipe_path(recipe.id) do %> 
          <div class='recipe-img-content2'>
            <% if recipe.image.attached? %>
              <%= image_tag recipe.image, class: "recipe-img" %> 
            <% else %>
              <%= image_tag "no-image.png", class: "recipe-img" , style: 'border: 1px solid gray;' %>
            <% end %>
          </div>
          <div class='recipe-info'>
            <h3 class='recipe-title'>
              <%= recipe.title %>
            </h3>
          </div>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/header" %>
<div class="recipe-show">

<%# 編集削除 項目 %>
  <div class="more">
    <ul class="recipe-show-list">
      <% if user_signed_in? && current_user.id == @recipe.user_id %>
        <li>
          <%= link_to '編集', edit_recipe_path(@recipe.id), class:"edit-btn" %>
        </li>
        <li>
          <%= link_to '削除', recipe_path(@recipe.id), data: { turbo_method: :delete }, class:"delete-btn" %>
        </li>
      <% end %>
    </ul>  
  </div>
<%# 編集削除 項目 %>

<%# レシピの概要 %>
  <div class="recipe-box">
    <div class="left-show-recipe">
      <h2 class="show-title">
        <%= @recipe.title %>
      </h2>
      <div class="recipe-img-content">
        <% if @recipe.image.attached? %>
          <%= image_tag @recipe.image, class: "recipe-show-img" %> 
        <% else %>
          <%= image_tag "no-image.png", class: "recipe-show-img" %>
        <% end %>
      </div>
    </div>
    <div class="right-show-recipe">
      <div class="detail-content">
        <h5 class="detail-recipe">材料</h5>
        <div class="detail-value">
          <% if @recipe.ingredient.empty? %>
            <div class="detail-URL">※レシピURL先の材料をご覧ください※</div>
          <% else %>
            <%= @recipe.ingredient %>
          <% end %>
        </div>
      </div>
      <div class="detail-content">
        <div class="detail-recipe">作り方</div>
        <div class="detail-value">
          <% if @recipe.instruction.empty? %>
            <div class="detail-URL">※レシピURL先の作り方をご覧ください※</div>
          <% else %>
            <%= @recipe.instruction %>
          <% end %>
        </div>
      </div>
      <div class="detail-content">
        <div class="detail-recipe">作ったレシピのURL</div>
        <div class="detail-value"><%= @recipe.reference_url %></div>
      </div>
      <div class="detail-content">
        <div class="detail-recipe">メモ</div>
        <div class="detail-value"><%= @recipe.memo %></div>
      </div>

      <%# いいね %>
      <div class="like_post-user">
        <div id="like-btn<%= @recipe.id %>">
          <%= render partial: "likes/like" , recipe: @recipe %>
        </div>
      <%# /いいね %>
        <div class="post-user">
          <%= link_to "投稿者：#{@recipe.user.name}", user_path(@recipe.user), class: "post-user-name" %>
        </div>
      </div>

    </div>
  </div>
<%# /レシピの概要 %>

<%# レシピとコメントの境界線 %>
  <div class="comment-border">
    <div class="border"></div>
  </div>
<%# /レシピとコメントの境界線 %>

<%# コメント欄 %>
  <div class="comments-index">
    <div class="comment-form">
      <% if user_signed_in? %>
        <%= form_with model: [@recipe, @comment], id: "comment-form" do |form| %>
          <%= form.text_area :text , class: "comment-text"%>
          <%= form.submit "コメントをする", class: "comment-submit" %>
        <% end %>
      <% end %>
    </div>
    <div id="comments">
      <h4>＜コメント一覧＞</h4>
        <% @recipe.comments.each do |comment| %>
          <div class="comment">
            <p class="user-info"><%= comment.user.name %>： </p>
            <p><%= comment.text%></p>
          </div>
        <% end %>
    </div>
  </div>
<%# /コメント欄 %>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>© CookDiary</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class='app-logo'>
    <%= link_to 'CookDiary', "/" , class: "app-name" %>
  </div>
  <div class='nav'>
    <ul class='lists'>
     <% if user_signed_in? %>
      <li><%= link_to current_user.name, user_path(current_user.id), class: "user-name" %></li>
      <li><%= link_to '投稿する', new_recipe_path, class: "post-btn" %></li>
      <li><%= link_to 'ログアウト',  destroy_user_session_path, data: { turbo_method: :delete }, class: "logout" %></li> 
     <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録',  new_user_registration_path, class: "sign-up" %></li>
     <% end %>
    </ul>
  </div>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%# cssはレシピ一覧のものを併用しています。
app/assets/stylesheets/recipes/index.css %>

<%= render "shared/header" %>

<%# レシピ一覧 %>
<div class="main-mypage">
<div class="mypage-recipes">
  <div class="recipe-contents">
    <h2 class='title'><%= @name %>さんのレシピ一覧</h2>
      <ul class='recipe-lists'>
      <% @recipes.each do |recipe| %>
      <li class='list'>
        <%= link_to recipe_path(recipe.id) do %> 
        <div class='recipe-img-content'>
        <% if recipe.image.attached? %>
          <%= image_tag recipe.image, class: "recipe-img" %> 
        <% else %>
          <%= image_tag "no-image.png", class: "recipe-img" , style: 'border: 1px solid gray;' %>
        <% end %>
        </div>
        <div class='recipe-info'>
          <h3 class='recipe-title'>
            <%= recipe.title %>
          </h3>
        </div>
        <% end %>
      </li>
      <% end %>
  </div>
  <%# /レシピ一覧 %>

  <div class="myrecipes-likes-index"></div>

  <%# いいね一覧 %>
  <div class="recipe-contents">
    <h2 class='title'><%= @name %>さんのいいねしたレシピ一覧</h2>
      <ul class='recipe-lists'>
      <% @like_recipes.each do |recipe| %>
      <li class='list'>
        <%= link_to recipe_path(recipe.id) do %> 
        <div class='recipe-img-content'>
        <% if recipe.image.attached? %>
          <%= image_tag recipe.image, class: "recipe-img" %> 
        <% else %>
          <%= image_tag "no-image.png", class: "recipe-img" , style: 'border: 1px solid gray;' %>
        <% end %>
        </div>
        <div class='recipe-info'>
          <h3 class='recipe-title'>
            <%= recipe.title %>
          </h3>
        </div>
        <% end %>
      </li>
      <% end %>
  </div>
</div>
</div>
<%# /いいね一覧 %>

<%= render "shared/footer" %>